yolo_model:

  config_file:
    name: yolov3-tiny_custom.cfg
  weight_file:
    name: yolov3-tiny_custom_3000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - obstacle
