yolo_model:

  config_file:
    name: yolov3-tiny_custom.cfg
  weight_file:
    name: yolov3-tiny_custom_2800.weights
  threshold:
    value: 0.2
  detection_classes:
    names:
      - person
      - obstacle
